### ISSUE TITLE
Function `getAccount` in SigningCosmWasmClient doesn't work properly

### ISSUE THREAD

**Issue by bldgk** [cosmos/cosmjs#702] opened 2021-03-11 12:21 UTC
Function `getAccount` in SigningCosmWasmClient doesn't work properly. Seems like js expects `Account` instead of `BaseAccount`
Response from the node with cosmos-sdk v0.41.0 
`{
  height: '1497',
  result: {
    type: 'cosmos-sdk/BaseAccount',
    value: {
      address: 'darc1rzdt9wrzwv3x7vv6f7xpyaqqgf3lt6phptqtsx',
      public_key: [Object],
      sequence: '2'
    }
  }
}
`
And code expects `cosmos-sdk/Account`
`if (responseData.result.type !== "cosmos-sdk/Account") {
                    throw new Error("Unexpected response data format");
                }`

Node versions:
	github.com/cosmos/cosmos-sdk v0.41.0
	github.com/CosmWasm/wasmvm v0.13.0
	
JS package 0.24.0

**Comment by webmaster128** [comment] 2021-03-11 12:32
This is a duplicate of https://github.com/cosmos/cosmjs/issues/537.

The problem here is that the Cosmo SDK broke their promise to provide a compatible LCD API by changing the type identifier from Launchpad to Stargate.

You are using @cosmjs/launchpad, right? I think the way forward would be to migrate to the @cosmjs/stargate package, that provides similar functionality. @cosmjs/stargate does not use the LCD API anymore. Instead it connects to Tendermint RPC. See https://gist.github.com/webmaster128/8444d42a7eceeda2544c8a59fbd7e1d9 for some starting points.

**Comment by webmaster128** [comment] 2021-03-15 17:22
The following output shows that API does not behave like an interface anymore but simply dumps the account object into JSON. This means opening of the check would only work for `BaseAccount` but not other types of account. So I don't see a point supporting Stargate backends with the Launchpad client.

```
$ curl -sS http://lcd.akash.forbole.com/auth/accounts/akash1qy0vur3fl2ucztpzcrfea7mc8jwz8xjmvq7qvy | jq .result 
{
  "type": "cosmos-sdk/PeriodicVestingAccount",
  "value": {
    "base_vesting_account": {
      "base_account": {
        "address": "akash1qy0vur3fl2ucztpzcrfea7mc8jwz8xjmvq7qvy",
        "public_key": {
          "type": "tendermint/PubKeySecp256k1",
          "value": "A/XsdhwSIKU73TltD9STcaS07FNw0szR4a+oDLr6vika"
        },
        "account_number": "56",
        "sequence": "27"
      },
      "original_vesting": [
        {
          "denom": "uakt",
          "amount": "166666670000"
        }
      ],
      "delegated_free": [
        {
          "denom": "uakt",
          "amount": "37190330000"
        }
      ],
      "delegated_vesting": [
        {
          "denom": "uakt",
          "amount": "166666670000"
        }
      ],
      "end_time": "1664114400"
    },
    "start_time": "1601042400",
    "vesting_periods": [
      {
        "length": "31536000",
        "amount": [
          {
            "denom": "uakt",
            "amount": "83333335000"
          }
        ]
      },
      {
        "length": "15638400",
        "amount": [
          {
            "denom": "uakt",
            "amount": "41666667500"
          }
        ]
      },
      {
        "length": "15897600",
        "amount": [
          {
            "denom": "uakt",
            "amount": "41666667500"
          }
        ]
      }
    ]
  }
}
```

**Closed by webmaster128** 2021-03-15 17:22 UTC

**Comment by chismo950** [comment] 2022-02-07 07:40
> https://gist.github.com/webmaster128/8444d42a7eceeda2544c8a59fbd7e1d9

use stargate to replace launchpad?

**Comment by sheriff-rango** [comment] 2022-06-16 07:37
I have got the same issue. Is there any solution with keeping using `@cosmjs/launchpad`?

**Comment by webmaster128** [comment] 2022-06-16 07:55
> Is there any solution with keeping using `@cosmjs/launchpad`?

Nope. `@cosmjs/launchpad` never supported connecting to a Cosmos SDK 0.40+ backend. If it worked for some things, it was luck. But it is known to be incompatible because Cosmos SDK changed the account structure in 0.40 (Stargate).
