### ISSUE TITLE
Get file build js of cosmwasm-stargate

### ISSUE THREAD

**Issue by solitarysp** [cosmos/cosmjs#1197] opened 2022-06-27 11:06 UTC
I need to use `cosmwasm-stargate`, but my application uses `thymeleaf` how do I use it?
Does it have a js build file?

**Comment by webmaster128** [comment] 2022-06-27 11:23
Does this answer help? https://github.com/cosmos/cosmjs/issues/1189#issuecomment-1163130219

**Comment by webmaster128** [comment] 2022-06-28 08:27
Closing as duplicate of https://github.com/cosmos/cosmjs/issues/1189

**Closed by webmaster128** 2022-06-28 08:27 UTC
